name: Android CI

on:
  push:
    branches: [ develop, release/*, feature/* ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout del repo
      - uses: actions/checkout@v4

      # JDK 17
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache de Gradle (super importante)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permissions to Gradle
        run: chmod +x gradlew

      # Linter Android (opcional pero recomendado)
      - name: Run Android Lint
        run: ./gradlew lintDebug --stacktrace

      # Unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      # Build APK debug
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # Guardar el APK como artefacto descargable
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
